---
- name: install httpd server 
  hosts: g1
  become: yes

  tasks:
    - name: Install HTTPD on CentOS or Amazon Linux
      dnf:
        name: httpd
        state: present
      when: ansible_distribution == "Amazon" or ansible_distribution == "CentOS"

    - name: Start Httpd on CentOS or Amazon Linux
      service:
        name: httpd
        state: started  
      when: ansible_distribution == "Amazon" or ansible_distribution == "CentOS"

    - name: Enable Httpd on CentOS or Amazon Linux
      service:
        name: httpd
        enabled: yes
      when: ansible_distribution == "Amazon" or ansible_distribution == "CentOS"

    - name: Install Apache2 on Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Start Apache2 on Ubuntu
      service:
        name: apache2
        state: started 
      when: ansible_distribution == "Ubuntu" 

    - name: Enable Apache2 on Ubuntu
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution == "Ubuntu"
