---
- name: Install Apache HTTP Server
  hosts: g1
  become: yes
  tasks:
    - name: Install Apache HTTP Server on CentOS
      when: ansible_distribution == 'CentOS'
      yum:
        name: httpd
        state: present

    - name: Start Apache and enable it to start on boot (CentOS)
      when: ansible_distribution == 'CentOS'
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install Apache HTTP Server on Amazon Linux
      when: ansible_distribution == 'Amazon'
      yum:
        name: httpd
        state: present

    - name: Start Apache and enable it to start on boot (Amazon Linux)
      when: ansible_distribution == 'Amazon'
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install Apache HTTP Server on Ubuntu
      when: ansible_distribution == 'Ubuntu'
      apt:
        name: apache2
        state: present

    - name: Start Apache and enable it to start on boot (Ubuntu)
      when: ansible_distribution == 'Ubuntu'
      service:
        name: apache2
        state: started
        enabled: yes
