---
- name: Build and Package with Maven 
  hosts: n4
  tasks:
    - name: Ensure ~/java-calculator directory is absent
      file: 
        path: "{{ ansible_env.HOME }}/java-calculator"
        state: absent
    
    - name: Create project directory
      file:
        path: "{{ ansible_env.HOME }}/java-calculator"
        state: directory
    
    - name: Clone GitHub repository (if needed)
      git:
        repo: "https://github.com/ctoweh/java-calculator"
        dest: "{{ ansible_env.HOME }}/java-calculator"

    - name: Build Maven 
      command: "mvn clean package"
      args:
        chdir: "{{ ansible_env.HOME }}/java-calculator"
