---
- name: Build and Package with Maven
  hosts: n4
  tasks:
    - name: Ensure project directory exists
      debug:
        msg: "Project directory exists."

    - name: Clone GitHub repository (if needed)
      git:
        repo: "https://github.com/ctoweh/java-calculator"
        dest: "~/java-calculator"
        version: main
      register: git_clone

    - name: Debug cloned files
      debug:
        var: git_clone

    - name: Download Apache Maven
      get_url:
        url: https://apache.osuosl.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
        dest: /tmp/apache-maven-3.9.6-bin.tar.gz

    - name: Untar Maven
      shell: tar -zxf /tmp/apache-maven-3.9.6-bin.tar.gz -C /opt
      args:
        creates: /opt/apache-maven-3.9.6

    - name: Update path for Maven use
      shell: echo 'export PATH=/opt/apache-maven-3.9.6/bin:$PATH' >> ~/.bashrc

    - name: Build Maven
      command: "mvn clean package"
      args:
        chdir: "~/java-calculator"
