---
- name: Build and Package with Maven 
  hosts: n4
  tasks:
    - name: Ensure project directory exists
      debug:
        msg: "Project directory exists."

    - name: Clone GitHub repository (if needed)
      git:
        repo: "https://github.com/ctoweh/java-calculator"
        dest: "~/java-calculator"
        version: main
      register: git_clone

    - name: Debug cloned files
      debug:
        var: git_clone

    - name: Build Maven 
      command: "mvn clean package"
      args:
        chdir: "~/java-calculator"
