---
- name: Fetch and Deploy Artifacts to Tomcat
  hosts: g1
  become: true

  tasks:
    - name: Remove existing *.war files from webapps folder
      ansible.builtin.file:
        path: "/opt/tomcat/webapps/{{ item }}"
        state: absent
      with_items:
        - "*.war"
      become: yes

    - name: List WAR files on Build Server
      ansible.builtin.shell:
        cmd: "ls /home/centos/java-calculator/target/*.war"
      register: war_files
      delegate_to: n4

    - name: Copy WAR files from Build Server to Tomcat
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/opt/tomcat/webapps/"
      with_items: "{{ war_files.stdout_lines }}"
      delegate_to: n4
      become: yes
