---
- name: Fetch and Deploy Artifacts to Tomcat
  hosts: g1
  become: true

  tasks:
    - name: Remove existing *.war files from webapps folder
      ansible.builtin.file:
        path: "/opt/tomcat/webapps/{{ item }}"
        state: absent
      with_items:
        - "*.war"
      become: yes

    - name: Copy WAR files from Build Server to Tomcat
      ansible.builtin.copy:
        src: "/home/centos/java-calculator/target/*.war"
        dest: "/opt/tomcat/webapps/"
      delegate_to: n4
      become: yes
