---
# handlers file for nexus

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes
        state: reloaded

    - name: Restart Nexus service
      ansible.builtin.service:
        name: nexus
        state: restarted


