---
# handlers file for nexus

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
    name: nexus.service
    state: reloaded


- name: Enable Nexus service
  ansible.builtin.service:
    name: nexus
    enabled: yes

