---
# handlers file for nexus

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes
        state: reloaded

    - name: Restart Nexus service
      ansible.builtin.service:
        name: nexus
        state: restarted
        
    - name: Enable Nexus service
      ansible.builtin.service:
         name: "{{ nexus_service_name }}"
         state: started
         enabled: yes



