---
## nexus

- name: Download Nexus
  ansible.builtin.get_url:
    url: "https://download.sonatype.com/nexus/3/latest-unix.tar.gz"
    dest: "/tmp/nexus.tar.gz"

- name: Extract Nexus archive
  ansible.builtin.unarchive:
    src: "/tmp/nexus.tar.gz"
    dest: "/opt/"
    remote_src: yes
    creates: "/opt/nexus-{{ nexus_version }}"
  register: extraction_result

- name: Create a symbolic link
  ansible.builtin.file:
    src: "/opt/nexus-{{ nexus_version }}"
    dest: "/opt/nexus"
    state: link
  when: extraction_result.changed

- name: Configure Nexus service
  ansible.builtin.template:
    src: "nexus.service.j2"
    dest: "/etc/systemd/system/nexus.service"
  vars:
    nexus_home: "/opt/nexus"  # Define nexus_home here
  notify:
    - Reload systemd
    - Enable Nexus service

- name: Start Nexus service
  ansible.builtin.service:
    name: nexus
    state: started
