- name: Set Java 11 as the active version on CentOS
  hosts: n1, n4
  become: yes
  tasks:
    - name: Check the available Java alternatives
      command: update-alternatives --display java
      register: java_alternatives
      ignore_errors: true

    - name: Set Java 11 as the active version
      command: update-alternatives --set java /usr/lib/jvm/java-11-openjdk-11.0.21.0.9-1.el7_9.x86_64/bin/java
      when: "'/usr/lib/jvm/java-11-openjdk-11.0.21.0.9-1.el7_9.x86_64/bin/java' not in java_alternatives.stdout"
